export TODO_DIR="$HOME/.local/share/todo"

if [ ! -f "$TODO_DIR/todo.cfg" ]; then
  mkdir -p $TODO_DIR
  cat > $TODO_DIR/todo.cfg <<EOF
export TODO_DIR="$HOME/.local/share/todo"
export TODO_FILE="$TODO_DIR/todo.txt"
export DONE_FILE="$TODO_DIR/done.txt"
export REPORT_FILE="$TODO_DIR/report.txt"
EOF
fi

alias up-todo="nvim $TODO_DIR/todo.txt"
alias todo="todo.sh -d $TODO_DIR/todo.cfg"

export TODAY="$(date +%a)"

function __build_prompt {
    local EXIT="$?" # store current exit code
    
    # define some colors
    local RESET='\[\e[0m\]'
    local RED='\[\e[0;31m\]'
    local GREEN='\[\e[0;32m\]'
    local BOLD_GRAY='\[\e[1;30m\]'
    # longer list of codes here: https://unix.stackexchange.com/a/124408
    
    # start with an empty PS1
    PS1=""

    if [[ $EXIT -eq 0 ]]; then
        PS1+="${GREEN}√${RESET} "      # Add green for success
    else
        PS1+="${RED}?️️️${EXIT}${RESET} " # Add red if exit code non 0
    fi
    # this is the default prompt for 
    PS1+="${BOLD_GRAY}\[\e[48;5;93m\]\[\e[38;5;27m\] \W \ue0c4 ${RESET}\$ "
}

# set the prompt command
# include previous values to maintain Apple Terminal support (window title path and sessions)
# this is explained in /etc/bashrc_Apple_Terminal
PROMPT_COMMAND="__build_prompt${PROMPT_COMMAND:+; $PROMPT_COMMAND}"

